# Generated by Django 3.0.5 on 2020-05-11 20:19

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planlistdetail',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='planlistdetail',
            name='json_content',
            field=jsonfield.fields.JSONField(blank=True, help_text='JSON content to display for plan', load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True),
        ),
    ]
