# Generated by Django 3.0.5 on 2021-01-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0007_auto_20201117_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(blank=True, help_text='dict of json allowed features for this plan', null=True),
        ),
    ]
