# Generated by Django 4.1 on 2023-04-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0011_alter_subscriptionplan_feature_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='extra_plan_cost',
            field=models.ManyToManyField(help_text='Extra plan costs a user can subscribe too at the same time', to='subscriptions_api.plancost'),
        ),
    ]
