# Generated by Django 4.1 on 2023-04-11 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions_api', '0012_usersubscription_extra_plan_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPromo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the promo', max_length=128)),
                ('code', models.CharField(help_text='the code of the promo', max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='the promo code amount', max_digits=19)),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='Percentage', max_length=12)),
                ('active', models.BooleanField(default=True, help_text='whether this promo is active or not.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, help_text='this promo can be use by this user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
