# Generated by Django 4.1 on 2023-04-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0013_subscriptionpromo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpromo',
            name='type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], default='Percentage', max_length=12),
        ),
    ]
