# Generated by Django 4.1 on 2023-11-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0014_alter_subscriptionpromo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancost',
            name='multiply_base_cost_quantity',
            field=models.BooleanField(default=False, help_text='When this cost is used as extra cost to another cost multiply it to the quantity of the cost first instead of adding it directly to the cost.'),
        ),
    ]
