# Generated by Django 4.1 on 2023-11-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0015_plancost_multiply_base_cost_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancost',
            name='is_main',
            field=models.BooleanField(default=True, help_text='whether this cost is the main cost in list of cost'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_trialing',
            field=models.BooleanField(default=False, help_text='whether this subscription is a on trial'),
        ),
    ]
