# Generated by Django 4.1 on 2023-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0016_plancost_is_main_usersubscription_is_trialing'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancost',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for cost', null=True),
        ),
    ]
