# Generated by Django 4.2.7 on 2024-02-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0017_plancost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancost',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for cost', null=True),
        ),
    ]
