# Generated by Django 4.2.7 on 2025-03-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0018_alter_plancost_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-active']},
        ),
        migrations.AddField(
            model_name='plancost',
            name='active',
            field=models.BooleanField(default=False, help_text='whether this cost is active'),
        ),
    ]
