# Generated by Django 4.2.7 on 2025-10-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0019_alter_usersubscription_options_plancost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancost',
            name='sequence',
            field=models.IntegerField(default=0, help_text='order by sequence '),
        ),
    ]
